---

#
# general configuration
#

- name: Run playbook-all_nodes-create_a_vimrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: Run playbook-all_nodes-minimal_tmux_configuration.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: Run playbook-all_nodes-minimal_bashrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: Run playbook-all_nodes-install_podman.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_podman.yml

- name: Run playbook-all_nodes-install_curl.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_curl.yml

- name: Run playbook-all_nodes-sysctl_allow_port_80_unprivileged.yml
  ansible.builtin.import_playbook: playbook-all_nodes-sysctl_allow_port_80_unprivileged.yml

- name: Run playbook-all_nodes-podman_socket_etc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-podman_socket_etc.yml

- name: Run playbook-all_nodes-create_containers.conf.yml
  ansible.builtin.import_playbook: playbook-all_nodes-create_containers.conf.yml

- name: Run playbook-all_nodes-output_URLs.yml
  ansible.builtin.import_playbook: playbook-all_nodes-output_URLs.yml
