---
- name: 'Nginx server'
  hosts: 'all'
  gather_facts: true
  become: false

  handlers:

    - name: Restart the nginx server container
      containers.podman.podman_container:
        state: started
        restart: true
        name: nginx-server

  tasks:

    - name: Create the nginx index.html
      ansible.builtin.copy:
        dest: /home/vagrant/index.html
        content: |
          Hello from vagrant-libvirt
        owner: vagrant
        group: vagrant
        mode: '0644'
      notify:
        - Restart the nginx server container

    - name: Create the nginx container
      containers.podman.podman_container:
        state: started
        name: nginx-server
        debug: true
        image: docker.io/library/nginx:latest
        publish:
          - '8080:80'
        volumes:
          - '/home/vagrant/index.html:/usr/share/nginx/html/index.html:z'
